### ISSUE TITLE
lru return unexpect result

### ISSUE THREAD

**Issue by hustcc** [lukeed/flru#4]
when the `prev` and `curr` is below:
```
cache.get('c');      // A=[c]       S=[d,a,e]
```

whether `cache.get('d')` will return true or false ?

**Comment by lukeed** [comment]
It will return true, just like the `cache.has('a'); //=> true` line below it (in the README).

It's a slightly modified LRU implementation, but still satisfies the requirements as it purges every `n + 1` – however, as described in the README, a maximum of `2n` items can be stored.

**Comment by lukeed** [comment]
Sorry, meant to close this since it's a question.

Feel free to follow up with additional questions, if any~!

Thanks!
